app:
  title: 'Phalcon Framework'
  name: 'Phalcon Website'
  author: 'Phalcon Team'
  description: 'Official Phalcon Documentation'
  keywords: 'php, phalcon, phalcon php, php framework, faster php framework, php extension, next generation framework, docs, documentation'
  email: 'team@phalcon.io'
  generator: 'Phalcon Team'
  analytics: 'G-CR3DKB9Q7P'

url: https://phalcon.io
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

include:
  - _pages
  - _redirects
  
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - serve
  - boxfile.yml
  - gen-contributors.php
  - updateData.php


